f-rating@v0.1.0 - initial code commit from generator. (#2158)
* f-rating@0.1.0 - Initial code commit from generator.

* f-rating@0.1.0 - Fix service dep versioning.

* Truborepo filter test

* Stop Browser tests from running if previous job fails

* Update changelog

* Revert test changes

* Remove unused env var

Co-authored-by: Ben Siggery <14013357+siggerzz@users.noreply.github.com>
Co-authored-by: Ben Siggery <bensiggery28@gmail.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -50,6 +50,7 @@ jobs:
       run: yarn --prefer-offline
 
   danger:
+    if: ${{ github.ref != 'refs/heads/master' }}
     needs: install
     runs-on: ubuntu-latest
     steps:
@@ -134,7 +135,7 @@ jobs:
     # Lint changed components if no root-level changes and not master.
     - name: Lint Changed Components
       if: steps.changes.outputs.global == 'false' && github.ref != 'refs/heads/master'
-      run: yarn lint --filter=[master] --concurrency=10 --cache-dir=".turbo"
+      run: yarn lint --filter=[origin/master] --concurrency=10 --cache-dir=".turbo"
     # Cache 'storybook-static'
     - name: Cache Storybook Static Directory
       id: storybook-cache
@@ -208,7 +209,7 @@ jobs:
     # Unit Test changed components + dependants if no root-level changes and not master.
     - name: Unit Test Changed Components + Dependants
       if: steps.changes.outputs.global == 'false' && github.ref != 'refs/heads/master'
-      run: yarn ci:test:${{ matrix.component-type}} --concurrency=10 --filter=...[master]
+      run: yarn ci:test:${{ matrix.component-type}} --concurrency=10 --filter=...[origin/master]
 
   browser-tests:
     strategy:
@@ -219,6 +220,13 @@ jobs:
     needs: build
     runs-on: ubuntu-latest
     steps:
+    # Run the following steps if previous jobs have succeeded to prevent wasting Percy screenshots.
+    - uses: technote-space/workflow-conclusion-action@v3
+    - name: Fail jobs if previous jobs failed.
+      if: ${{ env.WORKFLOW_CONCLUSION == 'failure' }}
+      run: |
+        echo "Not running browser tests due to a previous job failure."
+        exit 1
     # Checkout the Repo
     - name: Checkout
       uses: actions/checkout@v3
@@ -265,11 +273,9 @@ jobs:
       with:
         path: ./packages/storybook/storybook-static
         key: storybook-cache-${{ github.ref_name }}-${{ github.run_id }}
-    # Run the following steps if previous jobs have succeeded to prevent wasting Percy screenshots.
-    - uses: technote-space/workflow-conclusion-action@v3
     # Run Component / A11y / Visual Tests against all components if 'master' or root-level changes.
     - name: Run All Component / A11y / Visual Tests
-      if: ${{ (github.ref == 'refs/heads/master' || steps.changes.outputs.global == 'true') && (env.WORKFLOW_CONCLUSION != 'failure') }}
+      if: ${{ (github.ref == 'refs/heads/master' || steps.changes.outputs.global == 'true') }}
       run: |
         yarn storybook:serve-static &
         yarn ci:test-component:chrome:${{ matrix.component-type }} --concurrency=1 &&
@@ -277,12 +283,12 @@ jobs:
         yarn ci:test:visual:${{ matrix.component-type }} --concurrency=1
     - name: Run Changed Component / A11y / Visual Tests + Dependants
     # Run Component / A11y / Visual Tests against changed components + dependants if no root-level changes and not master.
-      if:  ${{ (github.ref != 'refs/heads/master' && steps.changes.outputs.global == 'false' && env.WORKFLOW_CONCLUSION != 'failure') }}
+      if:  ${{ (github.ref != 'refs/heads/master' && steps.changes.outputs.global == 'false') }}
       run: |
         yarn storybook:serve-static &
-        yarn ci:test-component:chrome:${{ matrix.component-type }} --concurrency=1 --filter=...[master] &&
-        yarn ci:test-a11y:chrome:${{ matrix.component-type }} --concurrency=1 --filter=...[master] &&
-        yarn ci:test:visual:${{ matrix.component-type }} --concurrency=1 --filter=...[master]
+        yarn ci:test-component:chrome:${{ matrix.component-type }} --concurrency=1 --filter=...[origin/master] &&
+        yarn ci:test-a11y:chrome:${{ matrix.component-type }} --concurrency=1 --filter=...[origin/master] &&
+        yarn ci:test:visual:${{ matrix.component-type }} --concurrency=1 --filter=...[origin/master]
     # On Failure - Upload Allure Report
     - name: Generate Allure Report
       if: failure()
